UUM-87263 Fix issue where macOS machines set to Morocco/Casablanca timezone were one hour behind
Unity-Technologies/mono pull request #2103
Opened 2024-12-20 16:38 UTC by kkukshtel-unity

Sourced from this fix from coreclr https://github.com/dotnet/runtime/pull/458/

More info on the fix context in this comment:
https://github.com/dotnet/runtime/issues/31331#issuecomment-549541031

- Should this pull request have release notes?
  - [ ] Yes
  - [ ] No
- Do these changes need to be back ported?
  - [ ] Yes
  - [ ] No
- Do these changes need to be upstreamed to [mono/mono](https://github.com/mono/mono) or [dotnet/runtime](https://github.com/dotnet/runtime) repositories?
  - [ ] Yes
  - [ ] No

Reviewers: please consider these questions as well! :heart:

**Release notes**

Fixed UUM-XXXXXX @username:
Mono: Your release notes go here.

2024-12-20 16:38 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/mono?pullRequest=2103) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/mono?pullRequest=2103) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/mono?pullRequest=2103) it.</sub>

2024-12-20 16:42 UTC, bholmes commented on external/corefx-bugfix/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs
> +                AdjustmentRule? r = !string.IsNullOrEmpty(futureTransitionsPosixFormat) ?
You have run into a problem with AdjustmentRule being nullable.  As it is a reference type, you may not need to add the ?.  Does the commit work without it?

2024-12-20 16:43 UTC, bholmes approved these changes
One item highlighted for nullable AdjustmentRule.  Otherwise LGTM

2024-12-20 16:44 UTC, bholmes commented
Actually you need some info filled out in the PR description section.

The release notes section and backports section needs filled out.

You will also need to create more PRs for backport branches, but land this first.

2024-12-20 16:46 UTC, UnityAlex requested changes
Please fill out PR's release notes section so they can be included when this makes it into a release.

2025-01-07 20:59 UTC, kkukshtel-unity commented on external/corefx-bugfix/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs
> +                AdjustmentRule? r = !string.IsNullOrEmpty(futureTransitionsPosixFormat) ?
@bholmes confirmed it does work! I was just copying the source fix here but it works fine without the annotation (built and tested).

2025-01-08 14:26 UTC, UnityAlex approved these changes
Looks good!

2025-01-08 18:33 UTC, merged